[project]
name = "nrl-scraper"
version = "0.1.0"
description = "extract data from nrl.com"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiometer>=0.5.0",
    "chompjs>=1.3.0",
    "httpx>=0.27.2",
    "pydantic>=2.9.2",
    "selectolax>=0.3.24",
]
